### ISSUE TITLE
Action Simulator is not working

### ISSUE THREAD

**Issue by veeru76** [actions-on-google/assistant-conversation-nodejs#33]
Request in the Simulator shows the following:
Invocation Error
You cannot use standard Google Assistant features in the Simulator. If you want to try them, use Google Assistant on your phone or other compatible devices.
![test](https://user-images.githubusercontent.com/54212169/115963608-ad0f9600-a53d-11eb-9785-a424ecef5c6b.png)

**Comment by actionsoneverything** [comment]
I had this issue recently, my action was working then suddenly my dev account couldn't trigger the action across browsers/devices.

The fix for me was to go to the test simulator settings, disable on-device testing, wait for it to disable testing, then to enable testing with my dev draft version, invocation immediately began working again.

**Comment by veeru76** [comment]
Thanks you it's working now

**Comment by hima2897** [comment]
Go to develop tab in the Actions console and give the display name. Then try to invoke the app. That resolved my issue.

**Comment by taycaldwell** [comment]
Closing as this issue seems to have been resolved.
